[package]
name = "tf-version-check"
version = "0.1.0"
authors = ["Kahlil Abreu <kahlil29@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensorflow = { version = "0.14.0", features = ["tensorflow_gpu"] }